### ISSUE TITLE
metadata_fn in report picks up operating system artifacts

### ISSUE THREAD

**Issue by ro6ert** [lpantano/seqcluster#15]
Hello Lorena,

I edited the summary.csv file and produced a new file with a tilde. This messed up the downstream processing of the report. Maybe the pattern could be changed to prevent this? (I just deleted the other file as a fix)

metadata_fn =  list.files(file.path(root_path), pattern = "summary.csv",recursive = T, full.names = T)
> metadata_fn
[1] "/redacted/sampleconfig/final/2016-04-19_sampleconfig/report/summary.csv" 
[2] "/redacted/sampleconfig/final/2016-04-19_sampleconfig/report/summary.csv~"

**Comment by lpantano** [comment]
thanks for the tip, hopefully this change fixed this case.
