### ISSUE TITLE
Regarding of fastq quality by collapse

### ISSUE THREAD

**Issue by hmkim** [lpantano/seqcluster#17]
Hi, Ipantano

I wonder about the quality score in fastq by collapse

> Methods
> 
> The new quality values are the average of each of the sequence collapse.

I think preserving the highest average quality score from fastq file is worth more than average for mapping.

**Comment by lpantano** [comment]
Hi, 

in this case is doing the average quality.

I don’t know if your question is related to something else. Then this quality will be used by the mapper, in case it can do it. Then, this will affect the MAPQ in the bam file and other tools can use this to detect SNPs, or related questions.

hope this help.

**Comment by hmkim** [comment]
seqcluster collapse use the average quality as you metioned.

In mapper, MAPQ caculated base on FASTQ quality score.

When the read have the highest quality score, the read's MAPQ will have higher than with average quality score,  right?
