### ISSUE TITLE
Unfamiliar output from bcbio

### ISSUE THREAD

**Issue by gnvalbuena** [lpantano/seqcluster#28]
I was running a smallRNA analysis on bcbio, and was expecting the output to be like previous analyses I have carried out, where each isomir is specified according to your naming convention. However, the results of my most recent analysis has been the following, which isn't particularly informative

[counts.txt](https://github.com/lpantano/seqcluster/files/1744314/counts.txt)

Is this expected? And if it isn't what's likely to be causing it?

**Comment by lpantano** [comment]
Hi,

sorry about the issues. Not sure exactly what is going on. Can you send me the files inside `log` folder and the `ls` of the final folder?

That file is the count for the `seqcluster` tool that is a general characterization of the data on the genome. It should be inside seqcluster folder. 

I am guessing you are not getting any miRNA files? 

If you send me those file I may have a better idea of what is going on.

cheers

**Comment by gnvalbuena** [comment]
Yes, I did take it from the seqcluster folder. in this instance, there weren't any other outputs in the main final folder. I had attached a truncated copy of the file, but there are more columns in the file corresponding to the samples analysed, sorry.

I'm attaching the contents of the log folder here: [log.zip](https://github.com/lpantano/seqcluster/files/1748490/log.zip)

`ls` of the final folder is here: [finalfolderls.txt](https://github.com/lpantano/seqcluster/files/1748523/finalfolderls.txt)

Thanks!

**Comment by lpantano** [comment]
Hi,

I think you don't have the small RNA data installed. 

Can I ask whether you are using bcbio_nextgen.py directly or using bcbio through other wrapper, like bcbio_vm.py, etc?

To have the small RNA data installed you can do:

`bcbio_nextgen.py upgrade -u development --tools --datatarget smallrna `

That assuming you can control that. If you are running bcbio through other tool, let me know and I can ping Brad to ask how to get it installed.

thanks
