### ISSUE TITLE
running from bcbio pipeline

### ISSUE THREAD

**Issue by ahsen1402** [lpantano/seqcluster#29]
Hi,
I like the report about mirQC you have shown in here: https://github.com/lpantano/mypubs/blob/master/srnaseq/mirqc/ready_report.md

Mostly, I wanted to create a barplot which has contribution of each type of RNA. As suggested I run seqcluster from bcbio to achieve this. However, in the upload folder I only see an HTML report from fastq and nothing similar shown in the above page.  I modified https://github.com/lpantano/seqcluster/blob/master/data/pipeline_example/mirqc/template.yaml

the template above to do this task. Am i missing something?

Second question I have is in the log file it says:

[2018-03-14T14:28Z] multiprocessing: seqcluster_prepare
[2018-03-14T14:28Z] You didn't specify any other expression caller tool.You can add to the YAML file:expression_caller:[trna, seqcluster, mirdeep2]

Is there a way to use all the capabilities without manually specifying them?

Thanks

**Comment by lpantano** [comment]
Hi,

So sorry about that. I have to change the config files to remove to run seqcluster always.

You can get that information adding this:

expression_caller: [seqcluster]

However, you will need to use the Rmd to get exactly that figure. Or use the bcbioSmallRNA package.

Cheers

**Comment by ahsen1402** [comment]
Thanks a lot. Upon your comment I checked the Rmd file ( i do not have time to run it) and in it there is the following code:

rRNA <- colSums(clus_ma[grepl("rRNA",ann) & grepl("miRNA",ann)==F,])
miRNA <- colSums(clus_ma[grepl("miRNA",ann),])
tRNA <- colSums(clus_ma[grepl("tRNA",ann) & grepl("rRNA",ann)==F & grepl("ncRNA",ann)==F & grepl("miRNA",ann)==F,])
rmsk <- colSums(clus_ma[grepl("ncRNA",ann) & grepl("rRNA",ann)==F & grepl("miRNA",ann)==F,])
total <- colSums(clus_ma)

dd <- data.frame(samples=names(rRNA),
                 rRNA=rRNA,
                 miRNA=miRNA,
                 tRNA=tRNA,
                 ncRNA=rmsk,
                total=total)
ggplot(melt(dd)) +
    geom_bar(aes(x=samples,y=value,fill=variable),
             stat='identity',
             position="dodge")+
    scale_fill_brewer(palette = "Set1")+
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

dd_norm = dd
dd_norm[,2:5] = sweep(dd[,2:5],1,dd[,6],"/")
ggplot(melt(dd_norm[,1:5])) +
    geom_bar(aes(x=samples,y=value,fill=variable),
             stat='identity',
             position="dodge")+
    scale_fill_brewer(palette = "Set1")+
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+


Do you think the seqcluster has been run on the data given I have commands related to it? I am trying to avoid to rerun everything as it took me about 10 hours for the first run.
Thanks

**Comment by lpantano** [comment]
Hi,

Yes, that is the part of the code to use. 

And, I don’t think so. But you can re-start from there and it will do only that part (although you’ll need to empty the checkpoint_parallel folder). If it is done, it should be inside seqcsluter/cluster folder. Do you have something there?

Cheers

**Comment by ahsen1402** [comment]
Thanks. I have 4 count matrices in the main analysis folder. Mainly, counts_mirna.csv, counts_novel.csv,counts.csv,counts_mirna_novel.csv , is there a description how these are generated.

**Comment by lpantano** [comment]
Hi,

The description of those files are here: http://bcbio-nextgen.readthedocs.io/en/latest/contents/outputs.html#small-rna-seq <https://bcbio-nextgen.readthedocs.io/en/latest/contents/outputs.html#small-rna-seq>

Hope this help, let me know if there are more questions.

Cheers

**Comment by ahsen1402** [comment]
Great thanks. I have some new data that has paired end reads how should I input them to the algorithm?

**Comment by lpantano** [comment]
Hi,

Currently the pipeline doesn’t support paired data, because the majority of the tools for small RNA work with single end. In principle you can use the first read file only and that would work.

Cheers
