### ISSUE TITLE
No UMI transform specified, assuming pre-transformed data.

### ISSUE THREAD

**Issue by jxshi** [lpantano/seqcluster#36]
Hi,

I tried to repeat the small RNA seq pipeline from bcbio-nextgen that you posted (https://github.com/lpantano/seqcluster/tree/master/data/pipeline_example/mirqc) . However, I got the following error message:
```
No UMI transform specified, assuming pre-transformed data.
No UMI transform was specified, but /data/proj/mirnatest/raw/SRR950876.fastq.gz does not look pre-transformed.
```

Can you check for me please?

Thanks for your help!

Best regards,

Jianxiang

**Comment by jxshi** [comment]
Hi,

I used the template yaml file that you provided [here](https://github.com/lpantano/seqcluster/blob/master/data/pipeline_example/mirqc/template.yaml).
I thinks something is wrong because the pipeline stopped after the error message showed up.

I have also tried to turn off ```umis``` tools off in the yaml file, and it didn't work.

Can you check further please? Thank you!

**Comment by lpantano** [comment]
Hi,

Thanks, I will try to reproduce, but I have recently run small RNA pipeline
with that config as it is and everything works.

It would be good if you could share the bcbio-nextgen-debug.log file to
help me figure it out what is happening.

Thanks

**Comment by lpantano** [comment]
Hi again,

I just pushed a fix, hopefully, that fixes it.

Please update bcbio to latest development and let me know. Sorry about this issue.

Cheers

**Comment by jxshi** [comment]
Thank you for your timely reply.

It took quite a long time to upgrade bcbio due to my slow internet connection. The small RNA-seq pipeline can now run without specifying umis.

Cheers!

Jianxiang
