### ISSUE TITLE
issue in seqcluster prepare

### ISSUE THREAD

**Issue by kisun** [lpantano/seqcluster#39]
HI, 
The command for running "prepare" step was:

`seqcluster prepare -c files-collapsed -o ${outdir}/prepd-seqs --minl 17 --minc 2 --maxl 45
`
The error message I got is:

`Traceback (most recent call last):
  File "/wrk/kipokh/DONOTREMOVE/bioconda3_env/bioconda_tools/bin/seqcluster", line 11, in <module>
    load_entry_point('seqcluster==1.2.4a14', 'console_scripts', 'seqcluster')()
  File "/wrk/kipokh/DONOTREMOVE/bioconda3_env/bioconda_tools/lib/python3.6/site-packages/seqcluster/command_line.py", line 25, in main
    prepare(kwargs["args"])
  File "/wrk/kipokh/DONOTREMOVE/bioconda3_env/bioconda_tools/lib/python3.6/site-packages/seqcluster/prepare_data.py", line 38, in prepare
    seq_l, sample_l = _read_fastq_files(f, args)
  File "/wrk/kipokh/DONOTREMOVE/bioconda3_env/bioconda_tools/lib/python3.6/site-packages/seqcluster/prepare_data.py", line 103, in _read_fastq_files
    with open_fastq(cols[0]) as handle:
AttributeError: __enter__
`
Can you please tell me what could I do to solve this issue?

Thanks!

**Comment by lpantano** [comment]
Hi, sorry for this error.

Can you show me what you have in the file `files-collapsed`?

Maybe the format is not the expected one.

cheers

Lorena Pantano, P.h.D

Research Scientist

Biostatistics Department

Harvard T.H. Chan School of Public Health

https://mirtop.github.io

https://lpantano.github.io


I'll be out of office from Dec-17th to Jan9th

**Comment by lpantano** [comment]
Can you tell me whether the file is separated with tabular or space between the two columns?

**Comment by lpantano** [comment]
Thanks,

Do you see the `INFO` line for all the samples or it stops at in the middle of the processing? is it the last sample showed in the console the one in the config file?

**Comment by kisun** [comment]
I can see INFO life for all the samples.

**Comment by lpantano** [comment]
Can you check if there is a empty line at the end?

**Comment by kisun** [comment]
For your reference i attached you the output files. 
[prepd-seqs.zip](https://github.com/lpantano/seqcluster/files/2784813/prepd-seqs.zip)

**Comment by kisun** [comment]
> Can you tell me whether the file is separated with tabular or space between the two columns?

Hi, does the sample ID need to be three-letter-code like for mirdeep2?

**Comment by kisun** [comment]
> > Can you tell me whether the file is separated with tabular or space between the two columns?
> 
> Hi, does the sample ID need to be three-letter-code like for mirdeep2?

It's now running smoothly by using new 3-letter-codes. Sorry for not trying this earlier. And thanks a lot for your effort.
Best wishes, Kisun

**Comment by lpantano** [comment]
oh!

Thank you for figuring it out! Good luck, let me know if you find other
issues.

Cheers

Lorena Pantano, P.h.D

Research Scientist

Biostatistics Department

Harvard T.H. Chan School of Public Health

https://mirtop.github.io

https://lpantano.github.io


I'll be out of office from Dec-17th to Jan9th
