### ISSUE TITLE
amchart - redistributable in source tree?

### ISSUE THREAD

**Issue by smoe** [lpantano/seqcluster#43]
Is ./misc/js/amcharts.js (from https://www.amcharts.com/download/) truly redistributable in your source tree? The license states "You can download and use all amCharts products for free. The only limitation of the free version is that a small amCharts logo will be displayed in the corner of your charts. If you’d rather have your charts without any branding, or you appreciate the software and would like to support its creators, please purchase a commercial license." It does not say that it may be redistributed.  If I am getting this right then you only need this referenced in your reports and this could then also just point to the online version, right? Would you accept a patch to reference the remote version on the CDN instead of a local copy?

**Comment by lpantano** [comment]
sure, go ahead!

**Comment by smoe** [comment]
What just came to mind - The jquery JavaScript files also have a reliable online presence via CNDs - see https://jquery.com/download/ . Shall I?
You may be right to redistribute Scribl.js . I have just created a Debian package for it and would then remove it from the seqcluster source tree for what Debian redistributes.
I would also address the Debian packaging of dragscrollable.js from https://github.com/mvlandys/jquery.dragscrollable, which would then free seqcluster from all exterrnal JavaScript in its source tree.

**Comment by lpantano** [comment]
sure, let's see it.
