### ISSUE TITLE
can python dateutils dependency go?

### ISSUE THREAD

**Issue by smoe** [lpantano/seqcluster#48]
Hello,

The dateutils package does not ship with a well-defined license (https://github.com/plytophogy/python-dateutils/issues/3), even though that license demands that the source ships with the license text. This has the effect that that dependency cannot redistributed. And seqcluster as a reverse depedency cannot either.

I just had a look if I could come up with a patch to remove that dependency, but, well, I failed to find any import from it. Can that beast possibly just be removed from setup.py and the dockerfile?

Many thanks!
Steffen

**Comment by lpantano** [comment]
I think it is fine, I remember having an issue with some of the dependency, that was asking about dateutils, but maybe it is not longer the case.

**Comment by smoe** [comment]
Hm. I just hierarchically went through all your dependencies and while there is a chance that I missed any such undeclared indirect dependency because I already had it installed on my machine and was sloppy in testing the package in a pristine environment, I am tempted to say that you may want to keep it in .travis.xml but remove it from your setup.py, which in my [limited!] understanding should only express dependencies of yours. And we should find the package that failed to express that dependency in their setup.py.

**Comment by lpantano** [comment]
I removed from everywhere and all the tests passed, so I think we are good. It is in `devel` branch, I will make a release soon, next week.
