### ISSUE TITLE
Unable to find documentation

### ISSUE THREAD

**Issue by SarahLuca** [lpantano/seqcluster#53]
Hello,
I am wondering about the following call to seqcluster that I found in a pipeline:
` seqcluster collapse -f reads -m 1 --min_size 15 -o some_folder`

What do the options `-m` and `--min_size` do?
Please let me know or point me to the documentation.

Thanks in advance!

**Comment by lpantano** [comment]
Hi, thank you for your question. That parameter is the minimum size of the sequences that will be kept in the output file. In this case, sequences less than 15nt are discarded. I hope this helped. Let me know. :)

**Comment by SarahLuca** [comment]
Thank you, that make sense.
What about '-m' ?

**Comment by lpantano** [comment]
I forgot to answer that, it is the minimum counts that the sequences need to have to be kept in the output file.

**Comment by SarahLuca** [comment]
Thank you!
