### ISSUE TITLE
MIRALIGNER/question

### ISSUE THREAD

**Issue by Alarabi1980** [lpantano/seqcluster#58]
Hi Lorena, 

Hope this email finds you well, 

I am working on miRNA seq data, and I am using your pipeline https://seqcluster.readthedocs.io/mirna_annotation.html to find Isomirs, but I am faced with some difficulties as the final output show me no results. so, I was wondering if I am making a mistake or something. one of the issues if in the pipeline page one of the file needed is miRNA.str? which I am supposed to download from mirbase. but there is not such file the only file available is mature.fa file is this the same? but when I use this file, it gives me an error that I am missing miRNA.str file? 
so, I changed the mature.fa file to mature.str and it worked with no error but no results? 

can you please help me 

Thanks 

command 
(bcbio) ahmed@ahmed-Precision-5570:~$ java -jar /home/ahmed/tools/miraligner.jar -sub 1 -trim 3 -add 3 -s mmu -i /home/ahmed/data/PEHmiRNA/collapse/trimmed_001.R1_trimmed.fastq -db /home/ahmed/data/PEHmiRNA/DB -o /home/ahmed/data/PEHmiRNA/collapse/output_prefix
Format is not tabular,guessing fasta
species found
Go to mapping...
Mismatches: 1
Trimming: 3
Addition: 3
Species: mmu
Feb 20, 2024 2:02:32 PM miraligner.map readseq
INFO: Tue Feb 20 14:02:32 EST 2024

Feb 20, 2024 2:02:32 PM miraligner.map readseq
INFO: Tue Feb 20 14:02:32 EST 2024

Reading reads
Feb 20, 2024 2:02:33 PM miraligner.map readseq
INFO: Number of reads excluded because size: 590697
Feb 20, 2024 2:02:33 PM miraligner.map readseq
INFO: Number of reads excluded because size: 590697
Feb 20, 2024 2:02:33 PM miraligner.map readseq
INFO: Number of reads to be mapped: 154078
Feb 20, 2024 2:02:33 PM miraligner.map readseq
INFO: Number of reads to be mapped: 154078
Feb 20, 2024 2:02:33 PM miraligner.map readseq
INFO: Searching in precursors
Feb 20, 2024 2:02:33 PM miraligner.map readseq
INFO: Searching in precursors
Feb 20, 2024 2:02:36 PM miraligner.map readseq
INFO: Tue Feb 20 14:02:36 EST 2024
Feb 20, 2024 2:02:36 PM miraligner.map readseq
INFO: Tue Feb 20 14:02:36 EST 2024
Feb 20, 2024 2:02:36 PM miraligner.map readseq
INFO: Num reads annotated: 38720
Feb 20, 2024 2:02:36 PM miraligner.map readseq
INFO: Num reads annotated: 38720

**Comment by lpantano** [comment]
Hi, I see the problem, it seems they stopped supporting that file. I would recommend to use STAR or bowtie to map reads to precursors and then use mirtop to parse the output and get isomir annotation.

```
bowtie \\
        -x \$INDEX \\
        -q <(zcat $reads) \\
        -p ${task.cpus} \\
        -t \\
        -k 50 \\
        --best \\
        --strata \\
        -e 99999 \\
        --chunkmbs 2048 \\
        --un ${meta.id}_unmapped.fq -S > ${meta.id}.sam
```

on another note you can use: https://nf-co.re/smrnaseq/2.2.4 to analyze everything and it will generate a lof results for this type of data.

**Comment by Alarabi1980** [comment]
Thank you so much Lorena!

**Comment by lpantano** [comment]
Hi,

can you share the input sample sheet you are using, please?

**Comment by Alarabi1980** [comment]
Hi Lorena, 

it worked, I just added this --max_memory 7.GB to the above command and it worked like magic!! Thanks a lot for your support! 
you are awesome!!

**Comment by lpantano** [comment]
oh, that is great! let me know if something else happens.
